
SELECT * FROM AIRCRAFT;                
SELECT * FROM CERTIFICATION;           
SELECT * FROM CERT_TYPE;               
SELECT * FROM COURSE;                  
SELECT * FROM COURSE_LESSONS;          
SELECT * FROM COURSE_TYPE;             
SELECT * FROM EMPLOYEE;                
SELECT * FROM EXAMINER_AUTHORIZATION;  
SELECT * FROM INSTRUCTOR;              
SELECT * FROM INSTRUCTOR_AUTHORIZATION;
SELECT * FROM LESSON;                  
SELECT * FROM LESSON_TASKS;            
SELECT * FROM PERSON;                  
SELECT * FROM PILOT_EXAMINER;          
SELECT * FROM STUDENT;
SELECT * FROM TRAINING_SESSION;